name: Test Build

on:
  workflow_dispatch:
  push:
    branches: ['dev', 'main']
  pull_request:
    branches: ['dev', 'main']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Install Rust toolchain
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          rustup target add wasm32-unknown-unknown
      - name: Install DFX
        uses: dfinity/setup-dfx@main
        with:
          dfx-version: '0.19.0'
      - run: dfx start --clean --background
      - name: Build and Deploy locally
        run: scripts/provision.sh
        env:
          IC_NETWORK: local
          CONTROLLER_PRINCIPAL: ${{ secrets.TEST_CONTROLLER_PRINCIPAL }}
          BATTERY_PRINCIPAL: ${{ secrets.TEST_CONTROLLER_PRINCIPAL }}
          BATTERY_API_KEY: testing
